
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ubaid
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        user_name = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        contact_no = new javax.swing.JTextField();
        cnic_no = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        confirm_password = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        sign_up_button = new javax.swing.JButton();
        return_to_login = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(800, 630));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Sign Up");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(399, 10, 80, 33);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(25, 49, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Email");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(25, 145, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(25, 97, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("CNIC No.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(25, 243, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Contact No.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(25, 193, 100, 32);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Password");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(25, 291, 100, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Address");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(25, 387, 100, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Confirm Password");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(25, 339, 100, 30);

        user_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        user_name.setToolTipText("");
        user_name.setSelectionColor(java.awt.Color.gray);
        jPanel1.add(user_name);
        user_name.setBounds(135, 55, 300, 30);

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setSelectionColor(java.awt.Color.gray);
        jPanel1.add(name);
        name.setBounds(135, 103, 300, 30);

        email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        email.setSelectionColor(java.awt.Color.gray);
        jPanel1.add(email);
        email.setBounds(135, 151, 300, 30);

        contact_no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        contact_no.setSelectionColor(java.awt.Color.gray);
        jPanel1.add(contact_no);
        contact_no.setBounds(135, 200, 300, 30);

        cnic_no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cnic_no.setSelectionColor(java.awt.Color.gray);
        jPanel1.add(cnic_no);
        cnic_no.setBounds(135, 249, 300, 30);

        password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password.setSelectionColor(java.awt.Color.gray);
        jPanel1.add(password);
        password.setBounds(135, 297, 300, 30);

        confirm_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirm_password.setSelectionColor(java.awt.Color.gray);
        jPanel1.add(confirm_password);
        confirm_password.setBounds(135, 345, 300, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setSelectionColor(java.awt.Color.gray);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(135, 387, 304, 126);

        sign_up_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sign_up_button.setText("Sign Up");
        sign_up_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_up_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(sign_up_button);
        sign_up_button.setBounds(135, 531, 130, 36);

        return_to_login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        return_to_login.setText("Go Back");
        return_to_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_to_loginActionPerformed(evt);
            }
        });
        jPanel1.add(return_to_login);
        return_to_login.setBounds(309, 531, 130, 36);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Or");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(277, 543, 22, 17);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jobapplication/signup_back.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(-40, -70, 840, 850);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 778));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sign_up_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_up_buttonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "thank you for using java");
    }//GEN-LAST:event_sign_up_buttonActionPerformed

    private void return_to_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_to_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_return_to_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cnic_no;
    private javax.swing.JTextField confirm_password;
    private javax.swing.JTextField contact_no;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    private javax.swing.JButton return_to_login;
    private javax.swing.JButton sign_up_button;
    private javax.swing.JTextField user_name;
    // End of variables declaration//GEN-END:variables
}
