/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jobapplication;

import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ubaid
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        user_name = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        signup_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        signin_clicked = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 630));
        setResizable(false);

        jPanel2.setPreferredSize(new java.awt.Dimension(800, 630));
        jPanel2.setLayout(null);

        jLabel2.setBackground(java.awt.Color.black);
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Sign In");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(380, 120, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Password");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(190, 310, 110, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Dont have an Account ?");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(320, 430, 200, 20);

        user_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        user_name.setSelectionColor(java.awt.Color.gray);
        jPanel2.add(user_name);
        user_name.setBounds(320, 230, 260, 30);

        password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password.setSelectionColor(java.awt.Color.gray);
        jPanel2.add(password);
        password.setBounds(320, 300, 260, 30);

        signup_button.setBackground(java.awt.Color.white);
        signup_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        signup_button.setText("Sign Up");
        signup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(signup_button);
        signup_button.setBounds(320, 470, 130, 36);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("User Name");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(190, 240, 110, 20);

        signin_clicked.setBackground(java.awt.Color.white);
        signin_clicked.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        signin_clicked.setText("Sign In");
        signin_clicked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_clickedActionPerformed(evt);
            }
        });
        jPanel2.add(signin_clicked);
        signin_clicked.setBounds(320, 370, 130, 36);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jobapplication/login.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signin_clickedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin_clickedActionPerformed
        if (user_name.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "User Name Required ","Invalid Username",HEIGHT);       
        }
        else if (password.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Password Required ","Invalid Password",HEIGHT);       
        }
        else{
           
        try{    
                Connection con=DriverManager.getConnection(  
                    "jdbc:mysql://localhost:3306/applicant_database","root","root@123");  
                
                Statement stmt=con.createStatement();
                ResultSet rs = stmt.executeQuery("Select user_name,pasword from user WHERE user_name = '"+user_name.getText()+"' and pasword = '"+password.getText()+"'" );  
                if (rs.next()){
                    JOptionPane.showMessageDialog(null, "Successfully Signed In","Success",HEIGHT); 
                    this.setVisible(false);
                    Dashboard db = new Dashboard();
                    db.set_name(user_name.getText());
                    db.setVisible(true);
                    
                }
                
                rs.close();
                stmt.close();
                con.close();  
               }catch(Exception e){ 
                   System.out.println(e);
               }
        }
    }//GEN-LAST:event_signin_clickedActionPerformed

    private void signup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_buttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        signup sp = new signup();
        sp.setVisible(true);
        
    }//GEN-LAST:event_signup_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton signin_clicked;
    private javax.swing.JButton signup_button;
    private javax.swing.JTextField user_name;
    // End of variables declaration//GEN-END:variables
}
